services:
  web:
    build:
      context: .
      args:
        LAST_UPDATED: ${LAST_UPDATED}
      dockerfile: Dockerfile
    container_name: paulcarlson.fi
    ports:
      - "127.0.0.1:8008:80" #host:container
    restart: unless-stopped
